### ISSUE TITLE
babel 7.beta31

### ISSUE THREAD

**Issue by TrejGun** [lodash/babel-plugin-lodash#196]
```
~/node_modules/babel-plugin-lodash/lib/index.js:105
      (0, _each3.default)(file.metadata.modules.imports, function (module) {
                                                ^

TypeError: Cannot read property 'imports' of undefined
    at PluginPass.Program (/Users/trejgun/projects/bike/node_modules/babel-plugin-lodash/lib/index.js:105:49)
    at newFn (/Users/trejgun/projects/bike/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/Users/trejgun/projects/bike/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/Users/trejgun/projects/bike/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/trejgun/projects/bike/node_modules/@babel/traverse/lib/path/context.js:95:12)
    at TraversalContext.visitQueue (/Users/trejgun/projects/bike/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/Users/trejgun/projects/bike/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/Users/trejgun/projects/bike/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/Users/trejgun/projects/bike/node_modules/@babel/traverse/lib/index.js:91:17)
    at traverse (~/node_modules/@babel/traverse/lib/index.js:58:12)
```

**Comment by jdalton** [comment]
Fixed by #194. Just need to review and bump.

**Comment by TrejGun** [comment]
thanks

**Comment by CentaurWarchief** [comment]
@jdalton any chance of republishing?

**Comment by jdalton** [comment]
v3.3.0 has been published 🎉
