### ISSUE TITLE
Cannot find module 'lodash-es' error when I upgrade to `3.3.1`

### ISSUE THREAD

**Issue by navarroaxel** [lodash/babel-plugin-lodash#203]
After upgrade from version `3.2.11` to `3.3.1` I'm getting the following error when I bundle my javascript with `webpack`:

```
Module build failed: Error: Cannot find module 'lodash-es'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (/src/gho-bo/node_modules/babel-plugin-lodash/lib/ModuleCache.js:107:58)
    at /src/gho-bo/node_modules/babel-plugin-lodash/lib/config.js:49:46
    at arrayEach (/src/gho-bo/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/src/gho-bo/node_modules/lodash/forEach.js:38:10)
    at config (/src/gho-bo/node_modules/babel-plugin-lodash/lib/config.js:47:22)
    at Object.<anonymous> (/src/gho-bo/node_modules/babel-plugin-lodash/lib/mapping.js:13:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src/gho-bo/node_modules/babel-plugin-lodash/lib/importModule.js:13:16)
    at Module._compile (module.js:570:32)
```
The `lodash-es` is a `devDependency` of this package and is not installed using the `npm install`.

**Comment by jdalton** [comment]
Hi @navarroaxel!

The issue should be resolved with v3.3.2.
