### ISSUE TITLE
ReferenceError: Symbol is not defined

### ISSUE THREAD

**Issue by mrchief** [lodash/babel-plugin-lodash#55]
I'm seeing this error and I'm not sure what I'm missing:

```
ReferenceError: Symbol is not defined
    at /home/app/node_modules/babel-plugin-lodash/lib/MapCache.js:83:10
    at Object.<anonymous> (/home/app/node_modules/babel-plugin-lodash/lib/MapCache.js:90:2)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/app/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.cls_wrapMethod [as _load] (/usr/lib/node_modules/newrelic/lib/shimmer.js:230:38)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

server.js
```js
require('babel-polyfill');
require('babel-core/register')({
  "presets": [ "es2015", "stage-0" ],
  "plugins": [ "lodash" ]
});
```

package.json
```js
"dependencies": {
    "babel-core": "^6.8.0",
    "babel-plugin-lodash": "^3.0.0",
    "babel-polyfill": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-stage-0": "^6.5.0"
},
```

**Comment by jdalton** [comment]
babel-plugin-lodash supports Node 0.12 and up.

**Comment by mrchief** [comment]
I tried with Node v4.4.3, v5 and v6. Same error.

**Comment by jdalton** [comment]
See https://travis-ci.org/lodash/babel-plugin-lodash/builds/127857222.
I'm guessing it's a bug in babel-polyfill.

**Comment by mrchief** [comment]
Seeing that its fresh off the oven, is there a new version in npm that I could try with?

**Comment by mrchief** [comment]
I think it may not be your issue at all. I found something on my end (it has to do more with how we deploy our apps).

**Comment by jdalton** [comment]
Word!

**Comment by mrchief** [comment]
Yeah that was it. Our auto deployer was defaulting to node v0.10 due to some bug on their part.
