### ISSUE TITLE
The plugin "lodash" didn't export a Plugin instance

### ISSUE THREAD

**Issue by gajus** [lodash/babel-plugin-lodash#7]
I keep getting the following error message when attempting to use "babel-plugin-lodash".

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: The plugin "lodash" didn't export a Plugin instance
    at PluginManager.validate (/pragmatist/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/pragmatist/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/pragmatist/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/pragmatist/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/pragmatist/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at DestroyableTransform._transform (/pragmatist/node_modules/gulp-babel/index.js:30:20)
    at DestroyableTransform.Transform._read (/pragmatist/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/pragmatist/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/pragmatist/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/pragmatist/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
```

What are some of the possible reasons for getting this error?

**Comment by gajus** [comment]
The error originates from "/pragmatist/node_modules/gulp-babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13":

```
PluginManager.prototype.validate = function validate(name, plugin) {
  // validate transformer key
  var key = plugin.key;
  if (this.transformers[key]) {
    throw new ReferenceError(messages.get("pluginKeyCollision", key));
  }

  console.log(name, plugin.buildPass, plugin.constructor.name);

  // validate Transformer instance
  if (!plugin.buildPass || plugin.constructor.name !== "Plugin") {
    throw new TypeError(messages.get("pluginNotTransformer", name));
  }

  // register as a plugin
  plugin.metadata.plugin = true;
};
```

`console.log(name, plugin.buildPass, plugin.constructor.name);` prints `lodash undefined LodashWrapper`. The problem is that `plugin.buildPass` is undefined.

What makes `plugin.buildPass` become undefined?

**Comment by gajus** [comment]
Appears to be some issue related with relative files. I have resolved the issue by giving babel an absolute path to the `babel-plugin-lodash` module:

```js
.pipe(babel({
    stage: 0,
    plugins: [
        require.resolve('babel-plugin-lodash')
    ]
}))
```

**Comment by megawac** [comment]
Thanks for reporting, I'll look into it tonight. I have a suspension that the issue is related to dynamically determining lodash paths. Did you have lodash installed in the source folders node_modules?

**Comment by john-kurkowski** [comment]
Getting this too. I never had Lodash anywhere in my project until this plugin.

It wasn't the relative paths issue. That just changes the error to

```
TypeError: The plugin "/path/to/my/cool/app/node_modules/babel-plugin-lodash/lib/index.js" didn't export a Plugin instance
```

**Comment by john-kurkowski** [comment]
I think my error is because babel-plugin-lodash requires Babel 6 and my project is stuck on 5. I got a little further by pinning to babel-plugin-lodash 0.2.0.

**Comment by megawac** [comment]
Yeah, the plugin API changed drastically in babel v6. Let me know if you
have further issues using pre-v1 versions with babel 5

**Comment by smashercosmo** [comment]
Get this error with v0.3.0. Babel version is 5.8.23.

**Comment by megawac** [comment]
Going to need more details. Unit tests pass https://travis-ci.org/lodash/babel-plugin-lodash/jobs/111081971#L160

**Comment by smashercosmo** [comment]
@megawac what extra data should I provide?

**Comment by megawac** [comment]
Can you give me a method to reproduce? As I've shown the unit tests pass with `babel@5`

**Comment by smashercosmo** [comment]
@megawac ok, here is the simple [repo](https://github.com/smashercosmo/babel-plugin-lodash-issue). just try to build it with webpack and you'll get this error.

**Comment by smashercosmo** [comment]
@megawac did you take a look at the repo?)

**Comment by megawac** [comment]
Haven't had a chance sorry.

**Comment by jdalton** [comment]
With Babel 6 stable I think it's time to drop pre 1.0 support of this plugin.
