### ISSUE TITLE
Plugin chokes on `export * from` syntax.

### ISSUE THREAD

**Issue by phyllisstein** [lodash/babel-plugin-lodash#77]
Hey there! I've been trying to integrate this lovely-looking plugin into my build pipeline, but it's throwing errors in modules that use syntax like this:

```js
// app/flux/reducers/index.js
export * from './issue';
export * from './pieces';
export * from './user';
```

When I run Babel with the Lodash plugin enabled, any module that uses that `export * from` syntax throws a variant on the following error:

```
ERROR in ./src/app/flux/reducers/index.js
Module build failed: TypeError: /Users/daniel/Repos/ignota/issues/issue0/src/app/flux/reducers/index.js: Cannot read property 'file' of undefined
    at PluginPass.ImportDeclaration (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-plugin-lodash/lib/index.js:105:26)
    at newFn (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/visitors.js:310:19)
    at NodePath._call (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/path/context.js:78:18)
    at NodePath.call (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/path/context.js:49:17)
    at NodePath.visit (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/path/context.js:108:12)
    at TraversalContext.visitQueue (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/context.js:174:16)
    at TraversalContext.visitSingle (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/context.js:124:19)
    at TraversalContext.visit (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/context.js:219:19)
    at Function.traverse.node (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/index.js:171:17)
    at traverse (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-traverse/lib/index.js:90:12)
    at File.transform (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-core/lib/transformation/file/index.js:548:35)
    at /Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-core/lib/transformation/file/index.js:563:16)
    at Pipeline.transform (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at transpile (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/daniel/Repos/ignota/issues/issue0/node_modules/babel-loader/index.js:88:12)
 @ ./src/app/flux/index.js 9:16-37
```

Without the plugin, the builds run and the exports are parsed as expected.

**Comment by jdalton** [comment]
Hi @phyllisstein!

What version of `babel-plugin-lodash` are you using?

**Comment by phyllisstein** [comment]
Hey there! I was using v3.1.4. After a little experimentation I determined that it seems to be a conflict with `babel-plugin-transform-runtime`: when I remove that plugin from my Webpack config, the Lodash plugin works great, but when I add it again I see the errors above. You can see the issue in action in [this repo](https://github.com/ignota/issue0/tree/babel-plugin-lodash), but I'm trying to put together a slimmer reproduction case as well. Will keep you posted.

**Comment by phyllisstein** [comment]
Here's a much more lightweight example of how to reproduce the error: <https://github.com/phyllisstein/lodash-repro-repo>.

Hope that helps! Let me know if I can furnish any more information.

**Comment by jdalton** [comment]
Thanks for the repro. Patched https://github.com/lodash/babel-plugin-lodash/commit/7afd0014c877b005a5ae3844d5fe8551fca8e011.

**Comment by phyllisstein** [comment]
Thanks so much! Appears to work like a charm. 💃
