### ISSUE TITLE
Plugin specified provided an invalid property __wrapped__

### ISSUE THREAD

**Issue by trueter** [lodash/babel-plugin-lodash#83]
Hey folks! Any idea how to go about this?
```
[0] Error: Plugin 4 specified in "base" provided an invalid property of "__wrapped__"
[0]     at Plugin.init (/Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/plugin.js:139:13)
[0]     at Function.normalisePlugin (/Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:174:12)
[0]     at /Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:208:30
[0]     at Array.map (native)
[0]     at Function.normalisePlugins (/Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
[0]     at OptionManager.mergeOptions (/Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
[0]     at OptionManager.init (/Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:488:10)
[0]     at File.initOptions (/Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/file/index.js:223:65)
[0]     at new File (/Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/file/index.js:140:24)
[0]     at Pipeline.transform (/Users/torsten/pixsy/pixsy-react/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
```

**Comment by jdalton** [comment]
Did you forget to `npm i` a plugin or preset?

**Comment by iest** [comment]
Just in case anyone else from the internet wondered in here — it seems the issue is caused **if webpack can't find the specified plugin.**

If like me you're using `require.resolve` in your webpack config, you need to use the full name of the plugin, like so:
```js
...
plugins: [
    'react-hot-loader/babel',
    'babel-plugin-lodash',
].map(require.resolve),
```

**Comment by stevenvachon** [comment]
I got this error with a global transform on a project that imports a file that had already been ran through Babel and Uglify.

**Comment by AndrewGrachov** [comment]
Got this inside reactcss

```
npm install babel-plugin-lodash
```

helped

**Comment by schuma7** [comment]
We're using next.js and noticed that this issue only occurred when npm install was invoked in production mode. The issue seems to be caused due to the way next.js handles transpilation. The solution was to move the babel-plugin-lodash from devDependencies to dependencies.

**Comment by bradennapier** [comment]
When doing `NODE_ENV="production" npm install` it will only install `dependencies` so you are missing your `devDependencies` - FYI to anyone that comes across this - thought I'd just provide the reason.
