### ISSUE TITLE
Module build failed: Cannot read property 'toLowerCase' of undefined 

### ISSUE THREAD

**Issue by joyfulelement** [lodash/babel-plugin-lodash#95]
Hi, 

With the upgrade to version 3.2.4, there seems to be a compatibility issue with lodash build and produces the following build error with webpack.

Here was the line up of the modules that resulted a broken build:

- lodash: **lodash@4.13.1**
- babel-plugin-lodash:  **babel-plugin-lodash@3.2.4**

```
Module build failed: TypeError: /build/workspace/test/src/js/containers/test.js: Cannot read property 'toLowerCase' of undefined
  [exec] at resolvePath (/build/workspace/test/node_modules/babel-plugin-lodash/lib/importModule.js:23:19)
  [exec] at importModule (/build/workspace/test/node_modules/babel-plugin-lodash/lib/importModule.js:38:25)
  [exec] at memoized (/build/workspace/test/node_modules/lodash/lodash.js:9870:27)
  [exec] at /build/workspace/test/node_modules/babel-plugin-lodash/lib/index.js:120:59
  [exec] at arrayEach (/build/workspace/test/node_modules/lodash/lodash.js:451:11)
  [exec] at Function.forEach (/build/workspace/test/node_modules/lodash/lodash.js:8634:14)
  [exec] at /build/workspace/test/node_modules/babel-plugin-lodash/lib/index.js:112:28
  [exec] at arrayEach (/build/workspace/test/node_modules/lodash/lodash.js:451:11)
  [exec] at Function.forEach (/build/workspace/test/node_modules/lodash/lodash.js:8634:14)
  [exec] at /build/workspace/test/node_modules/babel-plugin-lodash/lib/index.js:105:26
  [exec] at arrayEach (/build/workspace/test/node_modules/lodash/lodash.js:451:11)
  [exec] at Function.forEach (/build/workspace/test/node_modules/lodash/lodash.js:8634:14)
  [exec] at PluginPass.Program (/build/workspace/test/node_modules/babel-plugin-lodash/lib/index.js:95:24)
  [exec] at newFn (/build/workspace/test/node_modules/babel-traverse/lib/visitors.js:301:19)
  [exec] at NodePath._call (/build/workspace/test/node_modules/babel-traverse/lib/path/context.js:76:18)
  [exec] at NodePath.call (/build/workspace/test/node_modules/babel-traverse/lib/path/context.js:48:17)
  [exec] at NodePath.visit (/build/workspace/test/node_modules/babel-traverse/lib/path/context.js:106:12)
  [exec] at TraversalContext.visitQueue (/build/workspace/test/node_modules/babel-traverse/lib/context.js:167:16)
  [exec] at TraversalContext.visitSingle (/build/workspace/test/node_modules/babel-traverse/lib/context.js:118:19)
  [exec] at TraversalContext.visit (/build/workspace/test/node_modules/babel-traverse/lib/context.js:211:19)
  [exec] at Function.traverse.node (/build/workspace/test/node_modules/babel-traverse/lib/index.js:161:17)
  [exec] at traverse (/build/workspace/test/node_modules/babel-traverse/lib/index.js:83:12)
  [exec] at File.transform (/build/workspace/test/node_modules/babel-core/lib/transformation/file/index.js:548:35)
  [exec] at /build/workspace/test/node_modules/babel-core/lib/transformation/pipeline.js:50:19
  [exec] at File.wrap (/build/workspace/test/node_modules/babel-core/lib/transformation/file/index.js:563:16)
  [exec] at Pipeline.transform (/build/workspace/test/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
  [exec] at transpile (/build/workspace/test/node_modules/babel-loader/index.js:14:22)
  [exec] at Object.module.exports (/build/workspace/node_modules/babel-loader/index.js:88:12)
```

In the previous babel-plugin-lodash build 3.2.3, which was successful when building against the same version of lodash, this was the lineup:

- Lodash version: **lodash@4.13.1**
- babel-plugin-lodash:  **babel-plugin-lodash@3.2.3**

Note that the build environment was on ubuntu 14. Building on Windows doesn't seem to have this issue. Hope the information helps.

**Comment by jdalton** [comment]
Hmm the `name` param `importModule` should always exist and be a string.
Do you have a snippet I can check against?

**Comment by joyfulelement** [comment]
I have copied the content of `importModule.js` from the build machine.

```
'use strict';
Object.defineProperty(exports, "__esModule", {
  value: true
});
var _lodash = require('lodash');
var _lodash2 = _interopRequireDefault(_lodash);
var _mapping = require('./mapping');
var _mapping2 = _interopRequireDefault(_mapping);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
/*----------------------------------------------------------------------------*/
function resolvePath(pkgStore, name) {
  var base = pkgStore.base;
  var id = pkgStore.id;
  var lower = name.toLowerCase();
  var module = _mapping2.default.modules.get(id);
  if (!module.get(base).has(lower)) {
    base = base ? '' : module.findKey(function (map) {
      return map.has(lower);
    });
    if (!base) {
      throw new Error(['The \'' + id + '\' method ' + name + ' is not a known module.', 'Please report bugs to https://github.com/lodash/babel-plugin-lodash/issues.'].join('\n'));
    }
  }
  return id + '/' + (base ? base + '/' : '') + module.get(base).get(lower);
}
function importModule(pkgStore, name, file) {
  return file.addImport(resolvePath(pkgStore, name), 'default', name);
}
exports.default = _lodash2.default.memoize(importModule, function (pkgStore, name) {
  return (pkgStore.path + '/' + name).toLowerCase();
});
```

**Comment by jdalton** [comment]
Oh, I meant the JS code your transpiling that's having the issue.

**Comment by joyfulelement** [comment]
I didn't find any direct calls to `importModule()`. Is there any specific code that you're looking for? 
As far as I know, any JS file that contains the statement `import * as _ from 'lodash'` and the use of lodash results the build failure.

**Comment by jdalton** [comment]
> As far as I know, any JS file that contains the statement `import * as _ from 'lodash'` and the use of lodash results the build failure. 

Thanks that's it :D

**Comment by joyfulelement** [comment]
Amazing turnaround time for this fix, thank you @jdalton , much appreciated!
I assume this would be in the next release i.e. `3.2.5` ?

**Comment by jdalton** [comment]
Yep. I want to take a unit test cleanup pass before I bump. Expect it this evening though.
